### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by itsmedhaaz** [Danny-Nunez/StreamFlix#1]
Sir, how do I get the hash? Is it an M3u8 link? Or what? Let me know sir?

**Comment by Danny-Nunez** [comment]
This is not using a m3u8 link. This is using webtor with a json file that has all the hash links for torrent files

**Comment by Adhaaz** [comment]
How do I retrieve the hash, sir?

**Comment by itsmedhaaz** [comment]
> This is not using a m3u8 link. This is using webtor with a json file that has all the hash links for torrent files

Okay sir, I understand. Is this for films only sir? TV Series are not available?

**Comment by Danny-Nunez** [comment]
Only for movies

**Comment by Adhaaz** [comment]
> Only for movies

![IMG_20230510_101239](https://github.com/Danny-Nunez/StreamFlix/assets/75169859/8b311142-5748-4412-94fd-85eff0fb32f6)

Sir, why is mine even like this, there is an advertisement, then the download button disappears and turns into "Download at Webtor", how to solve it sir?
