### ISSUE TITLE
ads problem

### ISSUE THREAD

**Issue by ismailazdad** [Danny-Nunez/StreamFlix#2]
hi i clone your project but when i use the webtorrent player (desktop and mobile) i have annoying ads , how did you do to remove them ? 
thanks

**Comment by Danny-Nunez** [comment]
You will need to be a patreon supporter to remove ads and once you subscribe for any of the tiers you send them your domain name and they will white list your domain.Here is the linkPavel Tatarskiypatreon.comSent from my iPhoneOn Oct 1, 2023, at 5:24 PM, Azdad ismail ***@***.***> wrote:﻿
hi i clone your project but when i use the webtorrent player (desktop and mobile) i have annoying ads , how did you do to remove them ?
thanks

**Comment by ismailazdad** [comment]
Thanks for the fast response 👍
1$/month...

**Comment by Danny-Nunez** [comment]
No problem good look!Sent from my iPhoneOn Oct 1, 2023, at 5:37 PM, Azdad ismail ***@***.***> wrote:﻿
Thanks for the fast response 👍
